//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Galautdinov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTask
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int CustomerId { get; set; }
        public int DepartamentId { get; set; }
        public int EmployeeId { get; set; }
        public bool ReadyStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Departament Departament { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
