//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Galautdinov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformTask
    {
        public int id { get; set; }
        public int TaskId { get; set; }
        public int Platformid { get; set; }
    
        public virtual Platform Platform { get; set; }
        public virtual Task Task { get; set; }
    }
}
